#!/bin/bash
set -e
PATH="/usr/local/bin:$PATH"
trap "rm -f .git/tags.$$" EXIT

ctags --tag-relative -Rf.git/tags.$$ --exclude={.git,env,migrations,archive} --languages=-javascript,sql
mv .git/tags.$$ .git/tags
